### ISSUE TITLE
Make ENI plugin return consistent result as other plugin 

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-cni-plugins#21]
Make `Add` and `Del` command in eni plugin return a [`Result`](https://github.com/containernetworking/cni/blob/master/pkg/types/current/types.go#L136), to get rid of the error message caused by [`json.Unmarshal`](https://github.com/containernetworking/cni/blob/master/pkg/types/current/types.go#L31).

**Comment by aaithal** [comment]
Fixed with #30
