### ISSUE TITLE
IPAM Plugin: IP Address should not be a required field in config for DEL command

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-cni-plugins#26]
We should make the `ipv4-address` field optional for `DEL`. The plugin should accept either that or the unique ID and infer `ipv4-address` from unique ID. Additionally, the plugin should also ensure that when unique id is specified, it is actually unique and that multiple IP addresses do not point to the same ID in the key value store

**Comment by richardpen** [comment]
Merged #29
