### ISSUE TITLE
Bump CNI to either v0.5.2 or v0.6.0 and cniVersion to 0.3.1

### ISSUE THREAD

**Issue by squeed** [aws/amazon-ecs-cni-plugins#58]
The CNI spec v0.3.0 (which corresponds to repository version v0.5.1) has an error, where the library (libcni) called one fields "ips" and the spec called it "ip". From v0.5.1 to v0.5.2, the spec was bumped to v0.3.1 and the specification text was fixed to correspond to the existing code.

In other words, cni v0.5.1 does not correspond to its own specification. Practically speaking, since almost everyone uses libcni, there is no difference. However, for the sake of correctness, it would be good if the plugins took at least the bump to v0.5.2 so they support spec version v0.3.1.

**Comment by mssrivas** [comment]
closing this as this issue is over 4 years old
