### ISSUE TITLE
Pid and lease file format don't work on dhclient 4.3.3

### ISSUE THREAD

**Issue by lilida** [aws/amazon-ecs-cni-plugins#71]
Hi, 

I noticed this issue for the eni plugin. The issue only happens on my latest hosts. I must specify dhclient as the prefix for the lease (-lf) and pid (-pf) file. Otherwise, they will not be generated. This causes an issue in cleaning up as it depends on pid file to figure out the process. Without the pid file, the process keeps alive and the eni cannot be returned to host. 

Ex:
**With dhclient prefix:**
 [root@node-cmp-test-kubecluster-2-0a03c326:/home/lidali]#  dhclient -q -lf /var/lib/dhclient/dhclient4-ns-12:31:ec:27:b1:d6.leases -pf **/var/run/dhclient4-123.pid** eth0
 [root@node-cmp-test-kubecluster-2-0a03c326:/home/lidali]# ls /var/run/dh*
 dhclient4-123.pid  

**Without dhclient prefix**
[root@node-cmp-test-kubecluster-2-0a03c326:/home/lidali]# dhclient -v -lf /var/lib/dhcp/dhclientabc.leases -pf **/var/run/4-123.pid** eth0
 Internet Systems Consortium DHCP Client 4.3.3
 Copyright 2004-2015 Internet Systems Consortium.
 All rights reserved.
 For info, please visit https://www.isc.org/software/dhcp/
 Listening on LPF/dev5/12:02:ce:9f:a3:fc
 Sending on   LPF/dev5/12:02:ce:9f:a3:fc
 Sending on   Socket/fallback
 DHCPDISCOVER on dev5 to 255.255.255.255 port 67 interval 3 (xid=0xcbd9b84e)
 DHCPREQUEST of 10.3.229.97 on dev5 to 255.255.255.255 port 67 (xid=0x4eb8d9cb)
 DHCPOFFER of 10.3.229.97 from 10.3.192.1
 DHCPACK of 10.3.229.97 from 10.3.192.1
 bound to 10.3.229.97 -- renewal in 1481 seconds.
 
 [root@node-cmp-test-kubecluster-2-0a03c326:/home/lidali]# ls /var/run/4-123.pid
 ls: cannot access '/var/run/4-123.pid': No such file or directory

System information:
4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

However, this does happen on my old host:
4.14.13-01 #01 SMP 14.04.5-Ubuntu Wed Jan 10 21:53:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Any ideas?

**Comment by lilida** [comment]
I studied a bit on dhclient source code but didn't find out a clue.

**Comment by mssrivas** [comment]
closing this as this issue is over 3 years old
